###
# configure the db server
#
---

- name: update postgres access and listen for external hosts
  sudo: yes
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: update postgres configuration
  sudo: yes
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf
  notify:
    - restart postgresql

- name: ensure postgresql server is running
  action: service name=postgresql state=started
  sudo: yes

- name: ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db: db={{dbname}}

- name: create extension postgis
  action: command psql -d {{dbname}} -c 'CREATE EXTENSION postgis;'
  sudo: yes
  sudo_user: postgres
  ignore_errors: True

# - name: create extension postgis_topology
#   action: command psql -d {{dbname}} -c 'CREATE EXTENSION postgis_topology;'
#   sudo: yes
#   sudo_user: postgres

- name: ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{dbname}} user={{dbuser}} password={{dbpass}} priv=ALL

- name: ensure new user does not have unnecessary privileges
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{dbuser}} role_attr_flags=NOSUPERUSER
