###
# installs the necessary postgis packages
#
---

- name: ensure database packages are installed
  apt: name={{item}} update_cache=yes state=latest
  sudo: yes
  with_items:
    - postgresql-9.3
    - postgresql-9.3-postgis-2.1
    - postgresql-server-dev-9.3
    - python-psycopg2
    - postgresql-client
    - postgresql-contrib
